### ISSUE TITLE
Notification Alert for items that will be expiring in a few days

### ISSUE THREAD

**Issue by RoguedBear** [patzly/grocy-android#108]
Your app is such a great companion to for the grocy web app! I use grocy on a repurposed server laptop and the mobile app as the front end. 
I have an idea for a new feature: It would be nice if the app can show notification alerts when some products will be expiring in a few days.

Thank you for the app!

**Comment by MrJohnZoidberg** [comment]
Thanks for the kind words and your proposal. :)

We will think about how we can implement that. A hurdle can be that the app has to run in background and perform server requests in the background from time to time. For that, we have to experiment and try things out, because we didn't work with such parts yet.
But please be patient – I'm currently working on an internal redesign of the app, so this feature will come after that.
Next month I'm going to start working in a company and my brother too (we have just become adults), so we will sadly have less time to work on our app.

**Comment by igor-cali** [comment]
@MrJohnZoidberg What's the best way to get the expiring items from the app code (better if an array with the expiring date?
Thanks!

**Comment by MrJohnZoidberg** [comment]
@igor-cali How do you mean "from the app code"? Do you want to implement something?

**Comment by igor-cali** [comment]
@MrJohnZoidberg Yes. I drafted some structure, but I am not familiar with the 'database code' and API. That's why I am asking for hints.

**Comment by MrJohnZoidberg** [comment]
@igor-cali Okay nice, you can look in the StockOverviewViewModel file, there is
- the repository which loads volatile items from database. VolatileItem is an object where productId and volatileType is stored, and when iterating over the VolatileItems you can check for "volatileType == expiring" and  look the corresponding stockItem up with the productId (stockitems are loaded in a separate array from the repository).
- the DownloadHelper which updates the database after loading. dlHelper.updateData() takes class types of Models which should be updated with the call.

I hope this helps you to understand the code. :-)

**Comment by igor-cali** [comment]
@MrJohnZoidberg I am trying to get items with no success, from `MainActivity.java`.
It looks like I cannot access `VolitileItems` nor the `repository` since they are local or private.

Here's is my code:
```
    [...]
    StockOverviewViewModel viewModel = new ViewModelProvider(this).get(StockOverviewViewModel.class);
    viewModel.setOfflineLive(! isOnline());
    viewModel.loadFromDatabase(true);
    viewModel.downloadData();
    //viewModel.updateFilteredStockItems();
    MutableLiveData<ArrayList<StockItem>> StockItems = viewModel.getFilteredStockItemsLive();
    ArrayList<StockItem> items = StockItems.getValue();
    [...]
```

I always get a null `items` list. Any hint?

**Comment by MrJohnZoidberg** [comment]
@igor-cali Mmh thanks for trying to implement that feature, but I think you have not enough Android and/or Java knowledge to have a good implementation in the end (no offense). The MainActivity is not the right place to add such lines there and the way how you load the StockItems is also not right, sorry. And I can't explain how you can/should make it instead because then I can also do it myself... :)
I think it would be better if I implement this in the near future.

**Comment by igor-cali** [comment]
@MrJohnZoidberg no offense at all. If you like, I can upload the draft in my forkb(I implemented the whole setting structure and permissions fr a service notification ).

**Comment by MrJohnZoidberg** [comment]
@igor-cali Oh that would be great :) You can create a pull request if you want.

**Comment by igor-cali** [comment]
> Oh that would be great :) You can create a pull request if you want.

Just issued the PR. It does not include the modules I changed to handle the boot and the notifications, following your comments.
If you provide me with any hints on the modules you would process that in, I can rework and share.

**Comment by MrJohnZoidberg** [comment]
Thanks for your work on it, I almost finished the feature yesterday. Only the time picker is missing and I will improve the notification text.

**Comment by igor-cali** [comment]
@MrJohnZoidberg is there a plan for a new release including this?
