### ISSUE TITLE
Shopping mode improvement: Also display done entries (maybe at the bottom)

### ISSUE THREAD

**Issue by jo-me** [patzly/grocy-android#123]
Feature suggestion:

You can swipe an item on the shopping list to mark it as done. 
However after swiping you still have to tap the checkmark, so it takes  2 steps for each item.

It would be cool to reduce this to just a swipe to make it more easy to use when going through the store.
 
Not sure what the shopping cart swipe action button is about but maybe it can be removed via setting or one action on left swipe and the other on right swipe.

**Comment by jo-me** [comment]
Ah I see.

Personally, I like the shopping list screen more. There, I can see which items have been marked off and I can easily revert them.

The shopping mode is prone to accidentally hitting stuff when handling the phone in the shop. Then entries disappear without the user seeing it (if the toast is already gone).

It woudl be even better if the marked off items were moved to the bottom so that they don't distract from the open items.

**Comment by jo-me** [comment]
From my comments you may have noticed that I'm merely interested in a shared, efficient shopping list.  I don't particularly care about the other parts of Grocy. I'm evaluating Grocy in this regard and while the web interface is appauling, your app is quite nice 👍

**Comment by MrJohnZoidberg** [comment]
Yes, I already thought about making it possible to revert done in shopping mode (like other shopping list apps do, eg. "Bring!").
I will work on that when I have enough time, currently (in my free time) I'm working on internal code improvements. After that I can make the shopping mode more intuitive.

> From my comments you may have noticed that I'm merely interested in a shared, efficient shopping list. I don't particularly care about the other parts of Grocy. I'm evaluating Grocy in this regard and while the web interface is appauling, your app is quite nice :+1:

Thanks for your kind words, they are motivating us!

**Comment by jo-me** [comment]
If you are looking for inspiration, one of the best shopping list apps I found is Organizy. Its kind of un-fancy, but it does a really good job at minimizing user input efforts.
https://play.google.com/store/apps/details?id=com.organizy.shopping.list

It automatically adds new products (for later autocomplete) without explicitly having to maintain product lists or categories.
It has color coded categories, swipe to complete and restore items.
It misses sync/sharing, self-hostedness, widgets and shortcuts, though.

**Comment by MrJohnZoidberg** [comment]
Thanks for showing up this app – unfortunately there are some limitations in our app:

> It automatically adds new products (for later autocomplete) without explicitly having to maintain product lists or categories.

Unfortunately, this concept is incompatible with grocy because one the one hand, a product list is essential in grocy and on the other hand, the autocomplete suggestions in our app rely on the product list on the grocy server.
You can add an entry in a shopping list without a product, if only the notes field is filled. But in this way you don't have auto-completion...

> It has color coded categories

Yes, color coded categories would be an idea, but that doesn't make sense as long as grocy doesn't support it, because we don't want to store infos *only* on a local database, we always change something on a server (except in offline mode, but that's temporarily).

> swipe to complete and restore items

That's what we try to make easier in shopping mode :-)
We could eventually change the gesture from tap to swipe or make an option for that.
