### ISSUE TITLE
 Icons / Pictograms for products

### ISSUE THREAD

**Issue by FX7** [patzly/grocy-android#138]
Sorry for crossposting. But I'm not quite sure where the right place for this issue is.

I opened https://github.com/grocy/grocy/issues/1037 for the server. But maybe my intention can better be apointed by (only?) the android app.

I would love to not only see the text of an item, but also some kind of picture (better icon / pictogram). My first aproche would be to set some kind of picture in the server as "favorite" or somethink like that and then let this picture be displayed by the android app.

By the way: Thank you for the great work!

**Comment by MrJohnZoidberg** [comment]
Thanks for your motivating words!

In my opinion it only makes sense to add icon support to our app, if the server supports it. Because else it would need an extra database for that and this result in the requirement for backup & restore possibility. Currently, everything (except some settings) is synced with the server so we don't need to manage our own database (this would be too much work for us). And I think it would be best to continue this scheme.

I hope you can understand this. :-)
So after the server supports this, you can open this issue again. – Or you can write the challenging code by yourself, but that's not an option I think because it's kind of hard to read for "outsiders"...
