### ISSUE TITLE
Right area too empty

### ISSUE THREAD

**Issue by duylong** [patzly/grocy-android#16]
Hi,

Can you improve the display with the info (days, numbers ...) on the empty part on the right? 
It allows you to display more products without scrolling. On my tablet I only have 3 products in landscape mode.

**Comment by MrJohnZoidberg** [comment]
Please explain this issue more clearly and/or attach a screenshot, because we cannot reproduce it.

**Comment by duylong** [comment]
Have you ever tried in landscape mode? 

Currently each element takes 3 lines (product name, number and expiry date), it takes a lot of space when it's multi-line. The stock overview in Grocy shows a product by line, I find it more practical.

I find it a shame to lose so much space on the right, especially in landscape mode. For example: 
![Screenshot_20200530-220359_Grocy](https://user-images.githubusercontent.com/3019703/83338197-223d0180-a2c2-11ea-9b80-ec2db2b93db5.jpg)

**Comment by MrJohnZoidberg** [comment]
Ah, now we understand your problem.
We'll try to move the date line to the right in landscape mode – but we won't create a list overview with three columns like on the grocy website, because then the item height would be too low for a swipe gesture.

Btw: Thanks for reporting so much issues :)

**Comment by drohhyn** [comment]
Maybe we can re-open this or I can also create a new task.

I've just started with grocy and have a wall mounted tablet for managing our stock. I was puzzled when seeing the white-space an the right, but also understand the swipe gesture requirements.
What do you think about a card view (accessible via toggle?) for larger screens which adds the button for consumption into the card, so no need for a swipe gesture? Maybe 2 cols are enough, but this would double the amount of displayed products.
Thanks for the consideration and your work!

**Comment by patzly** [comment]
I will close this issue for now. Because my twin brother Dominic switched to Apple devices a while ago and doesn't actively use Grocy himself, he has withdrawn from the Grocy Android project. This means that I am now the sole maintainer of this now large project. I will continue to develop the app alongside my studies, my job and my other projects, as my free time allows, but l haven't enough time for big changes like this. I hope you understand, an update with many improvements is coming very soon and maybe you can enjoy some of my other app projects I spend my free time on alongside Grocy Android!
This issue may be re-opened in the future if someone wants to contribute with a pull request and needs some room for discussion.
