### ISSUE TITLE
Feature Request: In-Store UX

### ISSUE THREAD

**Issue by lpfann** [patzly/grocy-android#21]
Hello,
I really like your app and have been using it for a few weeks!
For now, I am using it for checking existing inventory.

I would like to also use the shopping list feature in the store when I am shopping.
Right now, I think the existing UI is too small when using the phone in one hand and carrying a bag or shopping cart in the other.
The 'checking off' swipe is not ideal in my opinion.
Besides Grocy I am using the [Bring](https://play.google.com/store/apps/details?id=ch.publisheria.bring&hl=en) shopping list app which has a very nice UX with big touchable tiles.
Do you have plans to improve the design?

I think an easy first improvement would be changing the ListView somehow to display the names of products in touchable rectangles.
In the future, you could also integrate product images.

Thanks again for your effort in developing this!

**Comment by patzly** [comment]
Thanks for your compliments and the nice suggestion!

Until now we had no plans to redesign the shopping list, as we think that it's clean and beautiful how it is. Moreover every list in the app has the same layout so it's consistent.

You're right that the UI is not big, that's not useful when we are under pressure at the supermarket. So we've decided to give your idea a try!
Unfortunately we have no plans to support images in the app, they're complicated to handle and require an extra lib which we've dropped yesterday... We think that product images are wasted time in daily life and unhelpful for a clean and fast management in a solid app. Furthermore products without an image would have nothing to display.

So your idea will probably end up in a new activity which is reachable with an app shortcut and with an action in the bottom bar of the shopping list. What the activity will probably look like:

- no bottom bar (not needed)
- list items (most product names are way too long for rectangles when they should be easy to read)
- big text, big touch targets
- rows are swipeable, they are done and disappear on a swipe
- rows clickable? There would've to be an undo option if you tap accidentally on an item
- no filters: "undone" is not necessary with disappearing items, "below min. stock amount" is not really needed as a filter when you're shopping
- no actions (because no editing needed)
- offline support #19 and syncing of done items when app has internet

I think of it like Android Auto, not "beautiful", but a simply helpful UX for the situation.
Do you agree with that or do you have other ideas?

**Comment by lpfann** [comment]
> So your idea will probably end up in a new activity which is reachable with an app shortcut and with an action in the bottom bar of the shopping list. What the activity will probably look like:

Sounds great.
In the following, I mostly describe the UX as I have experienced it in Bring and which works very well for me ( and my SO) when we go to get groceries.

>     * list items (most product names are way too long for rectangles when they should be easy to read)

With list items you mean 1 item per row? I think if you extend each row into 3 columns with one list item per column and increase the size of the box enough, even long texts should fit. 

>     * big text, big touch targets

Yes.

>     * rows are swipeable, they are done and disappear on a swipe

I think swipe gestures are always complicated when using a (big) phone with one hand.

>     * rows clickable? There would've to be an undo option if you tap accidentally on an item

I think it would be best two separate the list into two sections:
- "Need to buy" 
- "Bought/In shopping cart"

Both sections could be separated by a graphical element and should also have different coloring,
i.e. in Bring, _unbought_ items are red while _bought_ items turn green.

When clicking on a list item it should change color when it changes its status.
Before moving the item into the other list, one could introduce a timeout (e.g. 5 seconds) to allow an undo action, when a misclick happened.

>     * no filters: "undone" is not necessary with disappearing items, "below min. stock amount" is not really needed as a filter when you're shopping
>     * no actions (because no editing needed)

Exactly, the only action in-store should be _buying/adding to basket_ ( and the undo of course).

>     * offline support #19 and syncing of done items when app has internet

Offline support is always nice to improve reliability.
But online syncing while in-store is especially useful when you are shopping with someone else at the same time and using the same list, to know what items the other already bought/put in his basket.

> I think of it like Android Auto, not "beautiful", but a simply helpful UX for the situation.
> Do you agree with that or do you have other ideas?

That's a very good example and comparable.
I think good design is always finding a balance between aesthetics and function.

**Comment by MrJohnZoidberg** [comment]
Version 1.4.0 of our App is out now, do you like the new shopping mode?
Ideas for improvement are always welcome.
