### ISSUE TITLE
1.4.0 Release crashes doing anything, even on demo server.

### ISSUE THREAD

**Issue by bfayers** [patzly/grocy-android#24]
Scanning, shopping list in shopping mode, etc are all impossible and now result in instant app crashes.

**Comment by triagony** [comment]
I second that. 

Yesterday (14.6.2020), when I tested the android app for the first time, everything worked ootb.

Today, when I start the barcode scanner within the app, the scanner pops up for a sec but finally the whole app crashes (closes) without any hint what's wrong. As I don't know, where the logfile is stored (debug enabled), I don't know either where to get more information what this behaviour is caused by.

I just saw, that there was an update of the app on June 14th. Perhaps it has anything to do with that update? Reinstall didn't work.

Thanks in advance,

Triagony.

**Comment by patzly** [comment]
Thanks for reporting and sorry for the inconveniences!
New version with crash fixes is out now (`v1.4.1`), hope it works.

**Comment by patzly** [comment]
@triagony In `v1.4.1` you can find _Logs_ in the setting's menu. In future you can look there and make a screenshot for an issue report.

**Comment by triagony** [comment]
> Thanks for reporting and sorry for the inconveniences!
> New version with crash fixes is out now (`v1.4.1`), hope it works.

For me it's working again with v1.4.1. Thank you for your quick support! :)

**Comment by patzly** [comment]
Glad we could help!
