### ISSUE TITLE
Use App with Home Assistant and Home Assistant Cloud

### ISSUE THREAD

**Issue by RubenKelevra** [patzly/grocy-android#309]
Hey guys,

I've read the help information [here](https://github.com/patzly/grocy-android/blob/master/FAQ.md) but this doesn't really help me to understand what's wrong.

I have the latest Home Assistant (2021.2.1)running the latest Grocy Add-On (0.11.0) and I've subscribed Home Assistant Cloud to get a valid HTTPS certificate and tunneling through my NAT for my installation.

The URL of the WebGUI looks like this:

`https://abcabcabcabc.ui.nabu.casa/hassio/ingress/abcabc_grocy`

And the login and UI via the Webbrowser works flawlessly. But when pasted in the Android App (version 1.10.1) with a freshly generated API-key, the App complains about a "Not a valid grocy instance". 

Isn't the Add-On in Home Assistant supported? Your FAQ read that way.

**Comment by MrJohnZoidberg** [comment]
Hi,
sorry that the FAQ section is not working for your setup, it only describes what I have tested a few months ago with a Raspberry Pi and Home Assistant OS. So I didn't take Nabu Casa into account – and unfortunately I won't test it again with this service because I don't have enough time for that.
What I know is that you have to configure the Grocy Addon to have an open port which is exposed to the internet. Can you accomplish this with Nabu Casa?
There is a possible way which allows a connection without port opening (a user investigated this in #249), but for this I have also too little time for development/testing/maintaining.

So if port opening doesn't work for you, I don't know any other ways how you could connect to grocy on your platform with our app... Sorry for that.

**Comment by MrJohnZoidberg** [comment]
Good news:
I found a way to reach the Grocy API directly without port opening, maybe I can implement a way which does the authorization workflow in our app – but this won't be easy because network requests need to be reordered for that. I will close this issue and track the progress for that in #249.

If you have further questions, you can post them also in #249. Thanks!
