### ISSUE TITLE
[Feature request] Add database support government food warnings

### ISSUE THREAD

**Issue by ovz93br43v7** [patzly/grocy-android#342]
Hello,

would it be possible to add support for database of government food warnings so that the user would receive a warning when:
1. Having a product in stock which is possible affected.
2. Or when the user try to add a possible affected product to the stock

In Germany there is an government database for food warnings:
website: https://www.lebensmittelwarnung.de/bvl-lmw-de/liste/alle/deutschlandweit/10/0
rss: https://www.lebensmittelwarnung.de/bvl-lmw-de/rss/alle

I would assume that other countries also have such government databases, but I only know the German version.
I think this would be a really nice feature because there are so many warnings.

**Comment by MrJohnZoidberg** [comment]
Hey, that's a good suggestion. But I'm asking myself how we can look if a product is in the list., because names are different on every server I think. The barcodes are only in the attached pdf links and it would need much data volume to parse all pdfs from the list in background (I'm thinking about the rss feed of a specific Bundesland).

A solution would be to parse all pdfs from the products which are in the rss feed currently and always look for updates of the feed on app start. If there was an update, we can display an option to parse the new pdfs. This could be done in foreground then.

But the implementation would require some time because the described behavior above would need new pages and options. So we cannot say that this will come "soon"... Moreover we have not that much free time currently, sorry.

**Comment by samnewman86** [comment]
Imho, this should be a feature of grocyn server, not a specific frontend

**Comment by ovz93br43v7** [comment]
@MrJohnZoidberg No problem I didn't assumed that this could be done fast and easy. When you come the conclusion that this is not possible then feel free to close this request.

@samnewman86 Probably you are right.

**Comment by MrJohnZoidberg** [comment]
Ok, but I will simply let this issue open, just like Bernd does in his grocy repo.

**Comment by MrJohnZoidberg** [comment]
I've now decided to hold the issue list as small as possible because we both have not much time and want to concentrate on important issues... It's also really unlikely that I will implement this feature (because of the reasons above). So I will close this issue now.
