### ISSUE TITLE
Question: How to edit already translated strings on Transifex

### ISSUE THREAD

**Issue by InToSSH** [patzly/grocy-android#350]
Hi guys,
I have found some strings on the Transifex that could be translated better or that have typos in them, however I am not able to fix them, only post a suggestion. Since there are no coordinators or reviewers for the czech language, is it enough to post it as an suggestion and you will apply it, or is there any other way?

Thanks

**Comment by MrJohnZoidberg** [comment]
Hi, until now if a language was complete I selected all strings and clicked "review all". That means that translators cannot change the translations anymore.
I just saw that Bernd doesn't do this in his Transifex project, so in the grocy project all translators can always edit all strings.
I will now remove the "reviewed" status from all translations in our project, so that you (and all other translators) can edit strings, too.

Sorry, and thanks for asking. :-)
