### ISSUE TITLE
Duplicate FR language in Transifex

### ISSUE THREAD

**Issue by lapourgagner** [patzly/grocy-android#354]
Not a big deal but in Transifex there is "French (fr)" completed at 100% and "French (France) (fr_FR)" completed at 0%.
Maybe delete the second one to avoid duplicate.

**Comment by MrJohnZoidberg** [comment]
Mmh, but I wonder why a translator requested "French (France) (fr_FR)" then? Maybe he wanted more granular translations? The FR in "fr_FR" is the region which makes a translation more specific.

**Comment by cyberjacob** [comment]
Would the more specific `fr_FR` inherit the translations from the "generic" `fr` set?

**Comment by lapourgagner** [comment]
> 
> 
> Would the more specific `fr_FR` inherit the translations from the "generic" `fr` set?

Yeah if it is possible I think this is the best idea.
As a French speaker from France, "French (fr)" is fairly ok for me, probably a time loss to retranslate all for maybe just few minor modifications.

**Comment by MrJohnZoidberg** [comment]
I can copy all translations from "fr" to "fr_FR" – but everytime we update some strings, these strings have to be translated in both translations. So if you have the language fr_FR configured on your Android device and we update or create some new strings, you will have to complete also the fr_FR translation. Because I won't copy the translations every time we update sth.

Another option would be to delete the language fr_FR from Transifex, so all who have fr_FR in their Android can see the fr Translations. what do you prefer?

**Comment by lapourgagner** [comment]
I think the second solution is more sustainable and I don't really see what difference it could make between these two languages. Unless one feels able to actively maintain these two languages, it is easier to reduce the number, in my opinion.

**Comment by MrJohnZoidberg** [comment]
Ok thanks, I will do that.
