### ISSUE TITLE
System Dark Mode override

### ISSUE THREAD

**Issue by cdrfun** [patzly/grocy-android#368]
Currently it is possible to force dark mode when the system wife dark mode is disabled. But it's not possible to change to bright mode (what's the correct opposite of dark mode?) when the system has dark mode enabled. This would be useful in two scenarios at least:
1. Testing bright mode when system has dark mode on
2. Circumvent UI bugs which only appear in dark mode without the need to change the whole system appearance

As this is my first issue in the project I'd like to take the chance to say thank you. This is such a high quality app - especially UI wise - that I think grocy would only be half as useful to me if the app didn't exist. A big thank you, I really appreciate the hard work putting into it. You should consider some kind of sponsoring option.

**Comment by MrJohnZoidberg** [comment]
Thank you for your nice words and the suggestion!
Generally we test the UI always with both modes so there shouldn't be UI bugs which only appear with one mode. And testing  bright mode when system has dark mode on is IMHO not necessary because you can quickly toggle the mode with a tile in quick settings.
In the near future we maybe create a paid version of our app where a better scanner is implemented. This would then be available for free here on GitHub but for money (no subscription) in Play Store.

**Comment by patzly** [comment]
@cdrfun Please report the UI issues you see in dark mode (as separate issues or bundled in one)!
The interface should look good in dark mode, too, no matter what Android version you have.

**Comment by patzly** [comment]
I think we can close this issue, since switching to light theme is not necessary from my point of view. With the current settings, the system theme is used by default, which is probably what most users find best. When the system switches to dark (means the user has enabled this in the system settings) no app is actually needed in light theme anymore.
Please report the issues with dark mode so that you enjoy using it as much as the light one.

**Comment by cdrfun** [comment]
Just two more thoughts on that: 
1. It's possible to override the system light theme, so the app is in dark theme. The other way around is not possible, this seems inconsistent to me. 
2. You are asking for testers here (https://github.com/patzly/grocy-android/issues/266). It would be easier for them to test both 

If you still think this is not needed, you can close the issue of course.

**Comment by patzly** [comment]
1. We think it's not needed in this direction. When the system is dark, no app should be bright and make the user's eyes explode.
2. We don't want the testers to test the exact colors or the theme, we think there isn't much to test, the colors are ok how they are. It's more for reporting problems in connection with grocy.
3. If you find UI bugs please report them. We aren't aware of any theme related bugs yet.
