### ISSUE TITLE
Stock Overview request (2.0 for server 3.x)

### ISSUE THREAD

**Issue by Akirainblack** [patzly/grocy-android#388]
When clicking on an item in stock overview rather than displaying Default Location (3rd item down) display the current location of any stock:
e.g.
Ice Creams
Amount
3 packs
Default location
Freezer

becomes:

Ice Creams
Amount
3 packs
Current location
Freezer bottom shelf
Freezer top shelf

As it's a stock overview this makes more sense to me as you're looking for where your stock is.

**Comment by Saturo78** [comment]
It definitely makes sense to show the stock entries.
Often i want to know which one is the oldest to be consumed first.

**Comment by Akirainblack** [comment]
Hi, any news on when you might incorporate this?

**Comment by MrJohnZoidberg** [comment]
Maybe I will implement that soon. But I think the "stock entries" page is better for that, which will come after the final v2.0.0 release because it needs a lot of work for this one page and we're still thinking about the design (how we can display the info from a whole row like it is on the website on a small display).

But it like Saturo wrote, it makes no sense to display the default stock location of a product in the stock overview.

**Comment by MrJohnZoidberg** [comment]
The progress of the stock entries page is trackied in #403.
I think I won't change the default location on the product info bottom sheet because the server UI also displays only the default location there.

**Comment by Akirainblack** [comment]
If I go into stock entries, which is what we're doing when viewing stock I get:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/37367305/145008626-9ccfdc4e-4d57-4847-a3dc-7c074862e8e6.png">
Which shows you it's current location.

**Comment by MrJohnZoidberg** [comment]
I don't understand what you want to express with that... You have a screenshot of the stock entries page which is still not implemented in our app and which has the issue #403. I will work on that soon, that means I won't implement the same functionality in the product info bottom sheet (which was your initial wish).
