### ISSUE TITLE
Implement barcode page (on master product page)

### ISSUE THREAD

**Issue by mightypanders** [patzly/grocy-android#391]
When editing a product I try to add a barcode to the product, in the barcode view I see that no barcodes are present for my product and that I can add some by pressing the button below. The only buttons I can see are the options hamburger, the delete button and the save button.
I tried the apk on two devices both showed the same behaviour.  
Is this expected or a bug?

If any more information is needed I will gladly try to provide it.

I am running my Grocy Server on version 3.0.1 (recognized as supported in the app) if this is a necessary information.

**Comment by MrJohnZoidberg** [comment]
Thanks for this report, I simply did not implement these things yet.

**Comment by DHM47** [comment]
@MrJohnZoidberg @patzly I would like to help implement this feature. I have begun updating "MasterProductCatBarcodesFragment".
If any work has been made on this please share it so I can build on it. Otherwise, I will continue working on the existing code in "MasterProductCatBarcodesFragment"

**Comment by MrJohnZoidberg** [comment]
Hi, feel free to work on that part, I haven't finished it yet because I think this is quite some work to do (you need to create a form for editing and the logic behind it)... I hope you have knowledge with LiveData because we work with it in all forms, so it would be great if you orientate yourself on our code from other forms.

Happy coding! You can ask questions anytime here.

**Comment by DHM47** [comment]
I've made the barcode addition functionality, kindly check the commit on my fork.
For reference here's a GIF of the implementation. 
![VID-20210830](https://user-images.githubusercontent.com/6565963/131414994-c84146d1-a799-49d7-a179-67871b233062.gif)

Feel to provide ANY comments, on both the design and the code.

**Comment by MrJohnZoidberg** [comment]
That's great :) But I think that you are working too quick with implementation of scanning and form things, because in my opinion there should be a separate "Create/Edit barcode" fragment which opens after you click on a barcode or create a new one. The form fields don't belong to the list fragment, to keep things consistently in the app.

So nice work so far, I think that took quite some time for you, but it still needs a lot of changes to have an UX and UI which fits to the rest of the app. Please ask if you experience difficulties or have questions for the design. Thanks for your contribution!

**Comment by DHM47** [comment]
Thanks. 
Sure I can split the implementation over to its own fragment. And just to confirm, this sheet will open either by clicking the FAB button or clicking one of the barcodes.

This new fragment will contain the remaining parameters (quantity unit 'not editable', amount, store, and note).

Regarding the deletion of barcodes, I see two options, which do you feel is best? or both? 
-Deleting from the main list (see GIF) 
![21-08-31-03-33-10](https://user-images.githubusercontent.com/6565963/131423189-c236fb98-99fb-4bf3-ab5f-870830ced97d.gif)

-Deleting from the new fragment.



Note that I am working on showing the QU and store info in the list, as it seems it hasn't been implemented in the Adapter.

**Comment by MrJohnZoidberg** [comment]
Hi, yes that's good, it's not implemented yet in the adapter.
The two barcode deletion options are both very useful from my point of view, so like in other parts of the app it would be good to offer both options. The multi selection feature is very nice.

And yes, the create/edit fragment should open after clicking on a barcode and after clicking on the FAB.:+1:

**Comment by MrJohnZoidberg** [comment]
@DHM47 I've copied your edited files and I've almost finished the functionality (additional fragment with form). Thanks for your work! :)
