### ISSUE TITLE
network error (because inactive product)

### ISSUE THREAD

**Issue by felipemfa** [patzly/grocy-android#436]
was using no errors in alpha 1, however after upgrading to beta 2 network error appeared. in the logs I was looking at ".../api/stock/products/2". I tested the url via browser and returned the same error, apparently the product id as not found. so I used the url ".../product/2" and opened it for editing, I found that it had the active flag unchecked. when checking it, the system loaded normally. Apparently the app is not handling exceptions for products that are inactive, causing it to stop loading the others

**Comment by MrJohnZoidberg** [comment]
Hi, do you mean the "Stock overview" page where the error occurs?

**Comment by felipemfa** [comment]
> Hi, do you mean the "Stock overview" page where the error occurs?

no, on the first screen of the app:
![WhatsApp Image 2021-08-13 at 14 03 20](https://user-images.githubusercontent.com/2481536/129394568-96f703ed-325b-45f4-8ece-c1711fa1e8f5.jpeg)

**Comment by MrJohnZoidberg** [comment]
Thank, you've discovered a bug in grocy (the server application) and I've reported it. But I will try to fix the crash with our next version.

**Comment by MrJohnZoidberg** [comment]
I'm sorry, it's not possible to fix the crash without creating new problems when loading, so you have to wait for the fix at grocy side and until than you can delete the product or change the properties to avoid having it in the "missing products" filter (because the problem is that it appears in the response from the server even if it's inactive and then the app cannot get its product details from the server).
