### ISSUE TITLE
Unable to "cross off" shopping list items when permissions are set 

### ISSUE THREAD

**Issue by ITguy3118** [patzly/grocy-android#447]
I'm going to hazard a guess and say this is on the Grocy side of things, but starting here first since this is where the issue presents itself. 
I noticed tonight on my fiance's phone that she gets an error when marking off shopping list item's ( selecting the little check mark icon) 
I do not get the error on my phone. 
After looking further in the logs on her phone on the grocy android app i see the following message 

{timestamp} 9302 9331 E Volley : 9779 a.a: Unexpected response code 403 http://{grocyurl}/api/objects/shopping_list/12

I found out that if i enable full permissions for her inside of grocy, the error goes away
The only permissions I have disabled for her disallows User management (and everything in it's branches), and the ability to edit master data. 
I'm guessing this has to do with the ability to edit master data which i would think simply checking off a shopping item list would not be editing master data...but idk.  I imagine master data to be more like, products themselves, and chores and tasks, etc.  Not a shopping list.  

At the moment, I don't  feel that this is a bug on Grocy Android side, so simply looking for some feedback on the subject.

**Comment by MrJohnZoidberg** [comment]
Thanks for your detailed explanation – like you I think that this is an issue with grocy and not with Grocy Android.
#432 is a suggestion to display an appropriate error message for such cases, because now the app doesn't distinguish between the error codes.
The master data permission should not influence the shopping list, that's right – but it's an API thing which can only be fixed on grocy side. You can search if there is already an issue for that in the grocy repository and if not, create a new one for it.

**Comment by ITguy3118** [comment]
Thank you for the response, I would agree with that.
