### ISSUE TITLE
Optional due date

### ISSUE THREAD

**Issue by mod20388** [patzly/grocy-android#457]
This is a feature request. Currently, the app requires a due date when purchasing new items. This should either be optional or there should be an option to disable this. After all, the web/server version of grocy allows disabling due/best before dates entirely (maybe the app should be sensitive to that option?).

(On a side note, kudos for designing such a nice app! I'm using it everyday.)

**Comment by MrJohnZoidberg** [comment]
Hey, thanks for your nice words! This is indeed not right yet, but the issue is included in another one which combines all of them (#397): Deactivated due date, deactivated location tracking, deactivated "multiple shopping lists" and so on. That's what is still missing for the final v2.0.0 release. :)

**Comment by MrJohnZoidberg** [comment]
The issue #397 is closed, so the improvements will be in the next version which will be released tomorrow hopefully.
