### ISSUE TITLE
4 digits in decimal numbers

### ISSUE THREAD

**Issue by barbax7** [patzly/grocy-android#459]
grocy supports decimal numbers up to 4 digits. why does the app round to the second decimal place instead?

**Comment by MrJohnZoidberg** [comment]
Because we do not use the rounding system from the server. I think this would be a feature request - because it requires work on all places in the app where numbers are rounded.

**Comment by Karl625** [comment]
I'm currently having issues with this. Was support for 4 decimal places ever added to the android app?
My main concern is rounding errors when calculating prices. For example, if I add 500g of butter that costs $6 the android app will calculate the butter as costing $0.01 per gram and then since I have purchased 500g immediately calculates the value of the butter added to the inventory is $0.01 x 500 = $5. So even though I just input $6 as the price the value is immediately incorrect.

**Comment by Dreytac** [comment]
I've just run into this issue as well and I'd like to add my support for using the decimal place setting from the server. I currently have mine set to 6 on input, 2 on display. Rarely would I actually input 6 but it does help immensely with rounding issues.

**Comment by AndreMotard** [comment]
Exactly the same issue, and it prevents me from using the app even if it would be much more practical when returning from shopping. And it would be nice to know how many decimals are taken into account on the app directly, so as not to be fooled

**Comment by MrJohnZoidberg** [comment]
It's now implemented in the whole app :)
