### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by matejdro** [patzly/grocy-android#460]
Hello,

Thanks for your efforts for this app. I would like to to buy you a cup of coffee. Is there a donation link somewhere that I'm missing?

Thanks.

**Comment by MrJohnZoidberg** [comment]
Hey, we are happy to hear that you like our work and want to donate money to us. There is no donation link because we didn't have the time and motivation yet to go to a tax consultant and thus we don't know whether we should tax donations or not... And the second reason is that we now have the unlock app in the Play Store where you can buy it and donate money to us "indirectly" (we don't handle taxes in this case, because Google pays them already).
If you don't have Play Services on your device, you can send us money with PayPal (if you use that):
paypal.me/dozedler

Thank you very much!

**Comment by matejdro** [comment]
Found the unlock key, thanks!
