### ISSUE TITLE
[Question] Transifex organization merge

### ISSUE THREAD

**Issue by Tallyrald** [patzly/grocy-android#464]
First of all: Thanks for the app, I'm really enjoying it.

I started to work on the Hungarian translation (it was kinda abandoned so I'll restart it), however I noticed that this app is on a different Transifex organization than Grocy. I also saw #101 but didn't want to necro it hence this new issue.

So there is a big caveat in having 2 orgs: Translation memories are separate. Transifex creates a TM for each project and if the projects are in the same organization they can be linked. Unfortunately this doesn't work in the current setup. Linking TMs would have the benefit of:
1. Translation goes faster and should be fully consistent across the 2 projects
2. QA is easier and streamlined

I kind of suspect that it's too late to change the whole setup, but I thought it to still be worth mentioning. What do you think?

**Comment by MrJohnZoidberg** [comment]
Thanks, great to hear that you like our app.

The merge would have these advantages, that's true. But you need to know that we are fully independent developers, we have nothing to do with the author of the grocy server application. So it would be necessary that we integrate our project into a Transifex organization from another person we have never met.
It would be a bit difficult to handle the access things and the whole transfer of the project.

Another point is the technical part of our sentences. We use other placeholder schemes than the grocy server project I guess. So I don't think that the translation memory would be an advantage for sentences with placeholders, because they cannot work together. Please correct me if you know better.

And the third point is that my brother Patrick has other apps in the app stores (e.g. Doodle Wallpaper) and he would like to have the projects on Transifex bundled in one organization.

Sorry, if you have to translate a lot of strings twice because of that but on the other hand we have a lot of other strings which are not in the grocy server project. And many of the strings which are on the server UI have a comment in Transifex with the location where you can copy the translation from. So the translation memory is not such a big advantage like you wrote, in my eyes...

**Comment by Tallyrald** [comment]
Thank you for your explanation, the current setup is perfectly fine, it was just a suggestion in case you deemed it worthwhile. I'll have both projects open and make sure to have the exact translations in both Grocy and the app wherever possible.

A quick note about the TM: it's main purpose would be to auto-populate strings that are an exact match, placeholder schemes would have to be reviewed anyway.

Again, thank you for your time and explanation, I'll close the issue.
