### ISSUE TITLE
Unsorted lists when editing master data

### ISSUE THREAD

**Issue by Turysaz** [patzly/grocy-android#473]
When editing a product (and likely other things) in the master data view, the lists of product locations, groups, units etc. that pop up when selecting the according field are unsorted.

**Comment by MrJohnZoidberg** [comment]
Thanks, I will look into it in a few days.

**Comment by MrJohnZoidberg** [comment]
Thank you for your PR, I've changed some things a bit:
- quantity units are always required and therefore don't need a "None selected" option (I've removed it, it was my fault)
- The sorting and the "None selected" entry "logic" is now in the bottom sheet classes

I hope that there won't be any new bugs regarding these bottom sheets because I've edited code in many files. Feel free to test and report if there are bugs. Thanks!

**Comment by Turysaz** [comment]
Thanks for the info! I'll install a master build tomorrow and check all my regular use cases in the next days. If I stumble across something, I'll let you know. ;-)
