### ISSUE TITLE
Request: Recipes notebook

### ISSUE THREAD

**Issue by stmr** [patzly/grocy-android#475]
Hi,
I'm using the app for some whe and find it awesome. There is, however, one thing that I'm missing similar to the shopping list in function - Recipes notebook.
Basically a custom shopping list with your own categories (side, main, gravy) where you could see what's in stock and text around them.
This way it would be as simple as open recipe notebook, open recipe, see what you want to cook with all the ingredients and their availability at home. Extra nice would be to also specify the portions and do all the counting for the user + add the out of stock items to the shopping list accordingly.
Thanks for the great work you do, have a great new year.

**Comment by MrJohnZoidberg** [comment]
Hi, thanks for your nice words! I think you mean the recipes functionality which is available on the server interface, but not in our app. We will add it when we have time for it, because it will need lot of work... There's already an open issue for this feature (#148) so I will close this one.

Happy new year!

**Comment by MrJohnZoidberg** [comment]
Feel free to reopen this issue if you think that you mean another feature than the recipes functionality. :)
