### ISSUE TITLE
Improvie API URL matcher

### ISSUE THREAD

**Issue by gersilex** [patzly/grocy-android#48]
Hi. I just wanted to try out your app but I cannot enter the URL to grocy.

The URL is `http://grocy` but the regular expression you used enforces at least one colon. As per [RFC 1735](https://tools.ietf.org/html/rfc1738#section-5) the colon (and the trailing slash) are not required in a valid host.

This seems to be an issue with a library as I regularly see apps with this problem. Would you mind updating the validation?

Thank you in advance! really looking forward to trying out your app!

---
edit: It seems to happen here: https://github.com/patzly/grocy-android/blob/f94112954d027e46162ebf4b9326f2e362885ee3/app/src/main/java/xyz/zedler/patrick/grocy/LoginActivity.java#L155

`isHttpUrl(url)` is so simple and only checks the first few characters, so it should not be the source of the problem. (https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/webkit/URLUtil.java#234)

**Comment by MrJohnZoidberg** [comment]
Hi, thanks for the suggestion!
We now simply check for `http://` or `https://`. Volley does the rest for us because there is an UnknownHostException with "Invalid host" description if the server url is invalid. So we print an error message below the server field if the string doesn't contain `http://` nor `https://` or if there is an `UnknownHostException: Invalid host` from Volley.

We'll publish a new version of our app soon.
