### ISSUE TITLE
Option to delete product when swiping to the right

### ISSUE THREAD

**Issue by Fxsch** [patzly/grocy-android#482]
I want to delete products when swiping to the right instead of them staying there and being struck through

**Comment by MrJohnZoidberg** [comment]
Do you mean on the shopping list? Please be more precise when you describe an issue here.

**Comment by MrJohnZoidberg** [comment]
If you mean shopping list, then you can simply tap on an entry and tap on the delete symbol.

**Comment by Fxsch** [comment]
Yes, I mean the shopping list. Adding this isn't that important, it would just make it easier if you always want to delete products.

**Comment by MrJohnZoidberg** [comment]
Mmh yes I think that doesn't make much sense to add this option, because with the same amount of taps you can already delete an entry. Swiping is not meant to be a batch action... Did you know that you can also delete all entries marked as 'done'? This option is called "clear shopping list" and then you can choose "only done items".
