### ISSUE TITLE
Crash when adding item to shopping list

### ISSUE THREAD

**Issue by builderjer** [patzly/grocy-android#485]
I have a few products in the master list, and when I try and add one to the shopping list, the app crashes. Not sure how to get logs off my Android, bit if you tell me what you need, I'm sure I can get them for you.

**Comment by builderjer** [comment]
I do know how to debug things, I'm just not sure where to look for logs. I am familiar with the adb shell, but need to know where logs will be. I will even rebuild the app with a higher log level if needed. I would love to have this app work.

**Comment by MrJohnZoidberg** [comment]
Sorry for not answering, I just have more important things currently. You can enable debug logs in the settings category "Debugging" and after the crash occurs, you can see the log on this page (after clicking on "Logs"). You can also change the loglevel on that page with tapping on the three dots on the bottom. Then you can make a screenshot of the lines where the crash occured or you can select the full text and paste it here (that would be better because you don't have to search relevant lines). Thanks for your help!

**Comment by builderjer** [comment]
Thank you for getting back. I will post screenshots, but they don't seem to show a whole lot. Any idea where to actually find the log file? 
![Screenshot_20220220-064053](https://user-images.githubusercontent.com/34875857/154845479-4c451aa9-032c-4045-b8ec-f0822ee15339.png)
![Screenshot_20220220-064039](https://user-images.githubusercontent.com/34875857/154845482-5583e689-68a6-4522-9289-78fbe91d7a2a.png)
![Screenshot_20220220-064030](https://user-images.githubusercontent.com/34875857/154845483-74c5f3ed-dd65-4b48-ada3-e1eb307be935.png)

**Comment by builderjer** [comment]
Those are backwards. Bottom one is first.

**Comment by MrJohnZoidberg** [comment]
Thanks for the screenshots, you can see the system logs with `adb logcat` command. Our app displays this log but all lines which are not part of our app are filtered.

**Comment by MrJohnZoidberg** [comment]
I cannot reproduce the error or understand why it is there, can you tell me which Android version you have and where you installed our app from?

**Comment by MrJohnZoidberg** [comment]
Please give a step-by-step description on how you can produce the cash, because I see a weird occourence of `StoreAdapter` in your provided log (which technically means that you clicked somehow on a store entry in a list) – but on the page where the crash occurs there should be no possibility to select a store...

**Comment by builderjer** [comment]
Maybe we can close this?  I think that I wasn't selecting a list for the item to be put into. I guess it could still be a bug, as I feel it should warn that a required feild is empty instead of crashing the app

**Comment by MrJohnZoidberg** [comment]
Okay, I've improved that, thank you.
