### ISSUE TITLE
Any chance for an option to use the app offline?

### ISSUE THREAD

**Issue by najodleglejszy** [patzly/grocy-android#5]
I've just found Grocy after it showed up in the IzzyOnDroid F-droid repo, and absolutely fell in love with the design. Unfortunately, I currently don't have the means to run a self-hosted instance. Would it be possible in the future to add an option to just use the app with a local database stored on my device?

**Comment by MrJohnZoidberg** [comment]
Sorry, this is not possible because we use the API of the grocy server – so the server does all the stuff and the app only sends requests to it.
It would be way too much work to implement the server functionalities in this app.
Maybe you can find someone who is willing to host you an instance of grocy?

**Comment by najodleglejszy** [comment]
ah, that's a shame, but I get it. I guess I'll just have to look into hosting it myself some time in the future, then. one more excuse to get an RPi :)

**Comment by timokau** [comment]
Wouldn't it be possible to embed the grocy-server, i.e. just run it on the phone and interact with it on localhost? Its not quite the same, but for example the `syncthing` app does something similar.

I'd probably not use this feature myself (since I would also want to access the data on my desktop), just saw this issue and thought I'd leave the idea here. It would definitely decrease the friction of adoption.

**Comment by timokau** [comment]
> But I didn't find an easy way to set up a HTTP server together with PHP and SQLite on Android in an App.

Yes, I can imagine setting that up would be a bit of a pain. I'm not sure about the slowness though, modern smartphones are pretty fast. And as I mentioned, `syncthing` does something similar. I don't know if any PHP is involved, but they have a native binary that stays running in the background and also has a web interface.

I can understand that you may not want to work on this, but maybe it helps :)
