### ISSUE TITLE
Connecting with grocy in home assistant is confusing and buggy

### ISSUE THREAD

**Issue by justcop** [patzly/grocy-android#509]
As a home assistant grocy user, whenever I get a new phone it's time to reconnect it.

Unfortunately the process is not very intuitive as you first need to click manually enter, then this is the first time when home assistant is mentioned, in the text. If you read this carefully and click on it, the next section opens up but it isn't clear what to do until you click on the text to open up the explanations.

I then followed these instructions and got an error when scanning the barcode. I had to then reenter the details.
The only way I got it to work was to enter the homeassistant grocy barcode details manually, the ingress ID was particularly hard to find.

**Comment by MrJohnZoidberg** [comment]
> Unfortunately the process is not very intuitive as you first need to click manually enter

This is not right, you just have to scan the grocy QR code from the API token page and our app can see from the QR code whether you use Home Assistant or not. At least if you don't have an error with the scanner.

> I then followed these instructions and got an error when scanning the barcode. I had to then reenter the details.

The app navigates back to the barcode scanner if you click on the explanation so that the fields can be filled when you skip the barcode scanner previously.

> The only way I got it to work was to enter the homeassistant grocy barcode details manually, the ingress ID was particularly hard to find.

As I wrote above these things should be filled automatically. This is **not** the normal behavior. So the only thing which is not working is the barcode scanner – can you tell me which error it displays when you scan the grocy API QR code?

**Comment by KyleStilkey** [comment]
![Screenshot_20220331-203013](https://user-images.githubusercontent.com/6766223/161171745-738ce624-4f8f-412f-b230-7fd84853a33d.png)
This is the error I get when trying to add a new device. I'm not sure if something has changed with the recent update and is related to Home Assistant or the HS Addon but added my wife's phone last week and the only changes I have seen is the Grocy Addon being updated and Home Assistant updates happening or something else.

**Comment by justcop** [comment]
I had the same error

**Comment by MrJohnZoidberg** [comment]
Okay thanks for the details, indeed the version 0.17.0 of the grocy add-on changed the content of grocy API QR codes... Version 0.16.0 codes don't contain the server URL whereas 0.17.0 codes contain the server URL. So on the one hand this needs a fix in our app (I'm sorry, the next version will come in a few days and I already have the fix) and on the other hand this change is very good because the user doesn't have to fill the URL field manually.

**Comment by KyleStilkey** [comment]
Sounds good and I'll await for the update and report back once it's been pushed. Glad to see this change to be honest as it will just make things even easier for users going forward.
