### ISSUE TITLE
Add support for server version 3.3.0

### ISSUE THREAD

**Issue by leotzian** [patzly/grocy-android#514]
Please add support for server version 3.3.0,  my docker container updated automatically and the app is not working, although I deleted the container and returned to the 3.2.0 version the web version is working fine and it says it is 3.2.0 version, but the android app still says server version 3.3.0 not supported. I unistalled the app and installed again but still the same problem ( I had activated beta versions in playstore ). I don't know why android app thinks that the server version is still 3.3.0

**Comment by MrJohnZoidberg** [comment]
The support will come with the next version which will be released today or tomorrow. I will close the issue because it is already implemented in the code. :)

> and the app is not working

Mmh, an auto update is generally not something really bad, except if there are breaking changes in the grocy version. But the v3.3.0 doesn't have big breaking changes, so I think you only have to tap on the "ignore" button when the compatibility warning pops up.
Or why do you tell me that the app isn't working? Is there a crash or errors?

> I don't know why android app thinks that the server version is still 3.3.0

Yes that's weird, but I also don't know why...

**Comment by leotzian** [comment]
I had the above problem look at the screenshot
Until yesterday it was working fine
Today I had this problem, so I found out that the server updated to version
3.3.0
Although I rolled back to 3.2.0 I had the same problem
If I try demo I have the above although the version is 3.2.0 now
I don't understand it
The second screenshot it what I get when I log out and press the demo button


Στις Κυρ, 10 Απρ 2022, 17:28 ο χρήστης Dominic Zedler <
***@***.***> έγραψε:

**Comment by MrJohnZoidberg** [comment]
Unfortunately the screenshots are not visible to me...

**Comment by leotzian** [comment]
I pressed ignore as you said but I have Network error , The required data
could not be load completely.
The strange think is that I downgraded to server version 3.2.0 but grocy
android still give the error of not supported version  3.3.0
If I try the web version it is working fine and in about menu it says
version 3.2.0
Very strange though

Στις Κυρ, 10 Απρ 2022, 21:45 ο χρήστης Dominic Zedler <
***@***.***> έγραψε:
