### ISSUE TITLE
Feature: Set tare weight of new product from OpenFoodFacts, if known

### ISSUE THREAD

**Issue by CloCkWeRX** [patzly/grocy-android#537]
1. Scan a product from openfoodfacts.
2. If the product is found and
3. If the product has a weight in (g, kg, other weight measurement units)

Try to populate the tare weight field?

(Not sure if this is the entirely best idea, putting for discussion)
#507

**Comment by MrJohnZoidberg** [comment]
That's not what the tare weight feature is meant for... It is for households where e.g. cornflakes are stored in a box and the tare weight is the weight of the box without anything, so that grocy automatically calculates the remaining amount when something is consumed and weight after that.
So adding a product weight as a tare weight makes no sense...
