### ISSUE TITLE
Ignore same barcodes on purchase

### ISSUE THREAD

**Issue by Friskygote** [patzly/grocy-android#541]
Hello,

First of all, lovely application, thank you for your effort put into it!
One thing that surprised me a little and I think could be improved in the future is purchase menu especially in relation to barcodes. As I've found out, when I use the barcode to prefill all other fields Grocy-android won't let me save the purchase, instead showing me a dialogue that it failed to upload the barcode. I believe it's due to the fact barcode is already in the database. 
I think it would be best if grocy-android still prefilled the fields on scanning the barcode if one already exists but ignored the upload of the barcode. Current behavior feels a bit counterintuitive because you have to remove the barcode before "purchasing" for it to save the purchase.

**Comment by MrJohnZoidberg** [comment]
Hey,

when you scan a barcode on the purchase page which is already stored for a product on the server, the product and the barcode details will be filled automatically.
The other case is when you scan a barcode which is not know by grocy, then there should open a page "Choose product" and you can select an existing product or create a new one. After you finished this step, the barcode should be visible on the purchase page, together with the product.

And these two cases can generally never lead to the issue which you've reported, only if there's something wrong in your database... So please test it either with another grocy instance or insert screenshots here so that I can reproduce the behavior. Thanks :-)

**Comment by Friskygote** [comment]
Okey, I've re-checked again how to reproduce. What I apparently did was scan the bar 2 times or somehow got the bar number besides prefilling the details.  But here are steps to reproduce:
- Use "Purchase" option
- Scan a product with known barcode
- Scan it again (barcode number should be added below the name)
- Set all required values and hit purchase
- This should show up until you remove the barcode and hit purchase again V

![mleko](https://user-images.githubusercontent.com/7283122/167292128-5172ad36-e011-4427-b193-e8fd6ec66b5d.jpeg)

Now, it didn't happen exactly how I were describing it in the OP and I think this behavior is less problematic if it really happens only when you scan given product twice (which I apparently did somehow?) although I still feel like duplicate barcodes should be ignored.
