### ISSUE TITLE
Feature Request: Chores overdue tracking / time display 

### ISSUE THREAD

**Issue by SerinitySW** [patzly/grocy-android#549]
Thanks so much for this app, I greatly appreciate it and it works fantastic. A feature my household is missing is the ability to have overdue chores highlighted in red, and displaying the times for chores that have due times. Both would be greatly beneficial in getting my roommates to do their chores on time.

**Comment by MrJohnZoidberg** [comment]
Thanks for your nice words, I have implemented the changes now. :-)

> overdue chores highlighted in red

![grafik](https://user-images.githubusercontent.com/27244574/179370831-0339d40f-e1f1-4073-a9fc-1f36387b581e.png)
The color highlight in the screenshot is how it looks like in the current public version, do you want to have another appearance (because you mentioned it in the issue)?
