### ISSUE TITLE
Location of items doesn't change after "opening" them

### ISSUE THREAD

**Issue by AlexSchmitz222** [patzly/grocy-android#569]
While adding new groceries, one can choose  "default location" and "default consume location" (which as I understand is the place, the product will be moved to internally after you "open" it.) The product isn't moved tho. 

For ex. I add a "milk", which while unopened is stored in the pantry, which is what I enter as "default location". When I open the milk, I scan it and active the "mark as opened" function inside the app, after which it should be moved to the "fridge"  (I think), as "fridge" is the location I entered for "default consume location".

Am I doing something wrong here?
Maybe some further explanation inside the app might be helpful?

**Comment by MrJohnZoidberg** [comment]
There is an help button on the top app bar on the master product date page, where you can see the description of the option (which is the same as on the web server): "Stock entries at the location below will be consumed first."

So the option hast nothing to do with a location where an item will be moved to after opening. I think this feature is not available on grocy for now (but maybe I'm wrong). For that please open an issue on the [grocy server repository](https://github.com/grocy/grocy), or search for an existing issue.

**Comment by MrJohnZoidberg** [comment]
I'm sorry, I was wrong with my explanation - at least since the server version 3.3.1 ist available, there is also an option "move on open" on the master product page, so the feature you expect was introduced there.

If you already have server version 3.3.1, you can activate the option mentioned above on your server for your products, then the server should automatically move them to the default consume location. Our app will have this option in the upcoming version 3.0.0, so then you can also set the option there.

**Comment by martin-braun** [comment]
@dominiczedler But it would be nice to be able to enable "move on open" in the app itself. I made a new issue #614 for it. Thanks.
