### ISSUE TITLE
Donation and Country restrictions

### ISSUE THREAD

**Issue by vampirismtrueblood** [patzly/grocy-android#571]
Hi Grocy team,

being a dev myself, i can imagine the amount of work and effort you guys put into the development of both the server and the client (web/android) sides, and I tried to support you by purchasing the "Unllocker" on Gplay, but unfortunately it shows this app not supported in your country, and while I can get it free on github as you mentioned, I still want to give something back.

If you can enable payments in both Egypt and Philippines, would be great, or send me your paypal.

One last thing, please enable product picture upload via app, this is a fundamental feature <3 

Awesome work guys, and awaiting your response.

**Comment by patzly** [comment]
Hi and thank you for your kind words!

Just to clarify, we are independent from the [grocy server application](https://github.com/grocy/grocy). The server application is developed and maintained by Bernd Bestel, another German developer. And we, the creators of the "unofficial" but featured Grocy Android app, are two brothers who are both studying right now.

I have published the unlock app only in countries in which Google has to pay the value-added taxes, otherwise I would have to do this in each country and this would be ridiculous, don't know how that should be possible for free-time devs...
You can find the VAT docs [here](https://support.google.com/googleplay/android-developer/answer/138000?hl=en) and I cannot find Egypt and Philippines on this page, so they would fall under "other countries" as I described above and we don't want to get into troubles with authorities, so this will not change.

If you want to donate, you can do this on [PayPal](https://www.paypal.me/pzedler) and I will share the half of it with @MrJohnZoidberg. Thank you so much in advance! :)

Currently we both have a lot work, the next step for the upcoming months for this project will be a huge Material You redesign by me. File access on Android (like image upload would require) is a huge and complex topic on its own since Android 11, so this would be another big todo for the time after the redesign which is the next milestone for now :)
