### ISSUE TITLE
Kotlin & Compose

### ISSUE THREAD

**Issue by austinhodak** [patzly/grocy-android#650]
Hello! Sorry for opening an issue that's not really an issue 😄 I'm wondering if there's a specific reason you chose Java instead of Kotlin? And also if you'd consider PRs with Kotlin code since Java and Kotlin are inter-compatible. 

I'd like to tackle some issues but I haven't touched a Java file in any of my apps in years 😅 

And also while we are on the subject, same question about PRs with Jetpack Compose, as it is also compatible with XML views.

Thanks and I look forward to chatting!

**Comment by patzly** [comment]
Hi, I've started with Java for Android development a few years ago when I was still at school because Java is still a very popular language for Android, especially in (a-few-years-old) books to start Android development which I took as my first steps. So when I realized that Kotlin would have been probably a better and more modern starting point it was already too late, my apps were all written in Java and I had not the time to learn and rewrite everything in Kotlin. Also I already had taught my brother Java so he was able to develop Grocy with me. Now Grocy Android is a huge project and we both have not the time to rewrite things and none of us is fluent in Kotlin (that might change in the near future for me).
Because it would require a bunch of extra libs and dependencies only to support Kotlin in the project (which would make the apk bigger than just with Java as Kotlin is based on it) we **currently** sadly don't have the intention to add Kotlin support.
Further we don't have the intention to use Compose because Compose is not up-to-date with Material 3 and Material You, many components are still missing and marked as "planned" on the doc pages. MDC-Android is always up-to-date and it seems the teams at Google work much faster on that library than on Compose.
Google also uses Java for the MDC-Android lib and provides all code examples for this lib in that language, another reason why I think Java is not wrong for a modern project.
