### ISSUE TITLE
Feature Request: Android Wear Support

### ISSUE THREAD

**Issue by Man-in-Black** [patzly/grocy-android#651]
Hey,

first of all: I LOVE this app. It's so amazing and atm I'm completly change my old Shopping List with this.

But there is one thing I would love to see: An companion app for Android Wear. At least for the shopping mode.
That would simplify me shopping time even more as it is now.

Is this possible?

Thank you.

**Comment by patzly** [comment]
That's a good idea I already have thought about! But the time we have is currently very limited, so you probably still have to wait a few months until I can experiment with a wear module.
Thank you for your big compliment, hope you like the redesign!

**Comment by patzly** [comment]
Sadly I haven't time for this as a Wear OS app is a whole project on its own. Because my twin brother Dominic switched to Apple devices a while ago and doesn't actively use Grocy himself, he has withdrawn from the Grocy Android project. This means that I am now the sole maintainer of this now large project. I will continue to develop the app alongside my studies, my job and my other projects, as my free time allows, but I will not start big new features here like an Wear OS app because I myself simply use the phone while shopping.
