### ISSUE TITLE
"due-soon" notification should include overdue items

### ISSUE THREAD

**Issue by martin-braun** [patzly/grocy-android#661]
Sometimes, overdue items are still good to eat, but the notification points to "due-soon" items only. I think we would need the ability to filter for both at the same time in the first place and then it can be linked by the notification properly.

**Comment by dominiczedler** [comment]
Done :)

**Comment by martin-braun** [comment]
@dominiczedler God speed in here, nice! If I get the code, the new type is "not fresh" which contains all items that are soon due and over due which sounds like a good way to solve the issue. I also can spot the adjusted notification receiver to show non-fresh items instead, this looks great. Good job! =)

**Comment by dominiczedler** [comment]
Thank you! If you think the term "not fresh" can be improved you can propose something other, I just thought that "volatile" like grocy server uses the term internally doesn't sound good...
I'm now quickly fixing the next issue with items that have no own stock, so that the stock filtering doesn't have any problems anymore.

**Comment by martin-braun** [comment]
@dominiczedler "not fresh" is so much better than "volatile", great job! Can't come up with something better, either.
