### ISSUE TITLE
Request: adding deep-links

### ISSUE THREAD

**Issue by Auroria-code** [patzly/grocy-android#676]
This might seem random and is probably something that is hard to implement i guess, but i am trying to get to the shopping/consum overview over a nfc tag for easy access with my phone. I can open the app just fine with the applink, but i still need to go to the overview myself, which is annoying when cooking and consuming things as i go.

**Comment by codesalatdev** [comment]
I just built a version of the app that does this

Added NFC permissions and optional requirement to the app:
```xml
<uses-permission android:name="android.permission.NFC" />
<uses-feature android:name="android.hardware.nfc" android:required="false" />
```
And modified MainActivity's intent-filter:
```xml
<activity
      android:name=".activity.MainActivity"
      android:windowSoftInputMode="adjustNothing"
      android:exported="true">

  <intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <action android:name="android.nfc.action.NDEF_DISCOVERED"/>
    
    
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
  
    <data android:scheme="grocy"/>
  </intent-filter>

</activity>
```

Now I can create NFC Tags with a NDEF dataset in the first and an AAR in the second slot:
![Screenshot_2023-03-28-22-56-55-87_b464bf9abcb41b8bdfb405c129ee5faf](https://user-images.githubusercontent.com/10341765/228365156-952560e6-c2cd-42a0-b633-ef7ba6562d07.jpg)

Since I have very limited knowledge about Android Apps, I don't know how critical it is that you can open every Fragment from an NFC tag. Then again, you can also open any website by scanning a NFC tag, and it requires no user interaction so :shrug: 

Maybe @dominiczedler can chime in real quick if they have enough time. If this works out, I'd also open a PR.

**Comment by dominiczedler** [comment]
Should be working in the next version, thanks! I don't see a big security issue for that because you cannot destroy a server or hack the app with the functionality, you can only open fragments (which have an internal URI assigned) with it.
