### ISSUE TITLE
Support for custom product info api provider

### ISSUE THREAD

**Issue by cniry** [patzly/grocy-android#679]
OpenFoodFacts is a big site, but in my case, it returns dozens product names in random languages and in many cases OpenFoodFacts doesn't know my products.
 
I would like to create a tiny proxy api script, which will parse product info by EAN on my favorite online grocery shop and provide json response.

Would you be so kind as to add another classes like OpenFoodFactsApi and OpenFoodFactsProduct, but with GUI configurable url?   https://github.com/patzly/grocy-android/blob/23986e5cd1da8f721374702fc6df9f809818b190/app/src/main/java/xyz/zedler/patrick/grocy/api/OpenFoodFactsApi.java#L36

**Comment by patrick-mota** [comment]
If I can add a suggestion it would be to make possible to get the data from multiple url.

Since you can have world.openfoodfacts fr.openfoodfacts etc. etc. it would be usefull to add multiple providers and when you scan the ean code in the list you get "suggestions" with the "from" attribute so you know from which provider you got it.

It's the same api, just the url is different but it would require probably to implement a dynamic url (like @cniry said) and a different view list.

If I have time end of july I'll take a look if I can implement something (even if it's not merged, it would be useful at least for me :))

**Comment by patzly** [comment]
I will close this issue for now. Because my twin brother Dominic switched to Apple devices a while ago and doesn't actively use Grocy himself, he has withdrawn from the Grocy Android project. This means that I am now the sole maintainer of this now large project. I will continue to develop the app alongside my studies, my job and my other projects, as my free time allows, but l haven't enough time for big changes like this. I hope you understand, an update with many improvements is coming very soon and maybe you can enjoy some of my other app projects I spend my free time on alongside Grocy Android!
This issue may be re-opened in the future if someone wants to contribute with a pull request and needs some room for discussion.
