### ISSUE TITLE
Add purchases without counting total 

### ISSUE THREAD

**Issue by chuq00** [patzly/grocy-android#714]
When adding items to inventory it would make much more sense for each item you add for it to increment up the purchased amount instead of requiring me to count all of the items on hand. Doing it this way is incredibly difficult for an already tedious process of adding every single item to inventory.

**Comment by patzly** [comment]
I would say that this is a general issue for grocy and not specific for our companion app, please use the official grocy github project for that (and make sure to search for existing issues there first before open a new one). But I think this is what inventory exactly means, to count all existing items at oncee. If grocy is introduced in a household where already many products are existing, these products would be added with the inventory feature because they were not bought while grocy was in use. For you the purchase page is a much more suitable solution I think.

**Comment by patzly** [comment]
I will close this issue now as I think you didn't understand the difference between inventory and purchasing in Grocy, hopefully purchase was the behavior you needed.
