### ISSUE TITLE
Improve message shown when product not on server

### ISSUE THREAD

**Issue by dezok666** [patzly/grocy-android#718]
Hello, I'm having issues with adding new product via mobile app.
Steps to reproduce:

Go to purchases
scan barcode
tap add new product
fill in necessary data
and here is the problem: app requires to provide Barcode and QU conversions, but those fields aren't editable with error "Product is not on the server".
![Screenshot_2023-06-11-10-50-21-30_ded3d01f237383c8e0209ace216d3455](https://github.com/patzly/grocy-android/assets/48985656/e7cfcffe-6d77-4c40-ad3b-5658c7304494)

For the life of me, I can't figure out what I am doing wrong

Mobile app version: 3.2.1
Grocy Version 3.3.2
PHP Version 8.1.18
SQLite Version 3.34.1
OS Linux 5.15.93-sunxi https://github.com/grocy/grocy-desktop/issues/23.02.2 SMP Fri Feb 17 23:49:46 UTC 2023 armv7l

**Comment by dominiczedler** [comment]
Hey, thank you for the report - the barcodes and conversions are not required though. Maybe you thought that because they have a red message as subtitle. The two entries cannot be clicked because the product has to be stored on the server before. So I will improve the message which is shown when you click on these entries.

**Comment by dezok666** [comment]
I did try to save product before making a report, however when trying to save I get "network with". I am connected to my WiFi and few seconds earlier i could consume other product without issue.
![Screenshot_2023-06-11-13-21-36-87_ded3d01f237383c8e0209ace216d3455](https://github.com/patzly/grocy-android/assets/48985656/b0417320-dae3-47b4-a2bd-6cc4760a84fd)

**Comment by dominiczedler** [comment]
Mmh okay, this is not the intended behavior. Fact is that barcodes and conversions are not the problem here, but I can really improve the message "not on server".

If you get a "Network error" there could be possibly a request error to the server. Can you test the steps with the latest nightly build? (Here on Github on the release page) I've made a proper details view of the received error.

**Comment by dezok666** [comment]
Sure thing, that's in the error details:
com.android.volley.ClientError
	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:193)
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
