### ISSUE TITLE
Cant setup Grocy app with Home Assistant Grocy Addon

### ISSUE THREAD

**Issue by TRECpro** [patzly/grocy-android#720]
Trying to setup android Grocy app with the Grocy Addon. I keep getting the message "Not a QR code with a long-lived access token from Home Assistant."

Another message I received was "Connection was closed. Error: java.lang.RuntimeException: Can't create handler inside the thread Thread[Thread-36,5,main] that has not called Looper.prepare()"

I created a Long-Lived Access Token I get the message that says "Not a QR code with grocy API credentials"

Home Assistant is running version:
Home Assistant 2023.6.1
Supervisor 2023.06.1
Operating System 10.2
Frontend 20230608.0 - latest

Android  version 13 on a Pixel 5a

**Comment by Toothwitch** [comment]
I am not the maintainer of this project, but i can answer this question (please delete if unwanted):

You created an Long-Lived Access Token within Home Assistant. This Access Token is for the Home Assistant API. 
To generate the correct Token for the Grocy Android app you need to create an API Token within Grocy. 
In the Desktop Browser Layout, the button for the menu is the wrench on the top right side. 
In the Mobile Layout it is under the Settings option in the burger menu. 
There is an option to manage your API Keys/Tokens. The Keys/Tokens generated there will work with the app.

**Comment by dominiczedler** [comment]
Thank @Toothwitch, I hope that helps. I didn't answer anything until now because I don't have much time right now and didn't know how this issue could be solved as it is all working with my instance.

@TRECpro Please answer if this helped and I will reopen the issue if not. In the upcoming release there is also a new hint to indicate which QR code should be scanned (HA or grocy).
