### ISSUE TITLE
Update error when stable release and nightly installed

### ISSUE THREAD

**Issue by vanMacG** [patzly/grocy-android#759]
I had stable release 3.2.1 installed, alongside with a newer nightly version (+ unlock key).
Both could be used alongside without problems.

When I tried to update the stable release to 3.3.1 today, I got an "error -13" telling me something about an already existing identity provider.
I'm on Android 11 (LineageOS 18.1).
After uninstalling nightly (+ unlock key), the update 3.2.1 -> 3.3.1 for the stable version worked without issues.

I don't know if this is a general issue or just my device (settings). Also it doesn't affect the usage of the app itself. I just wanted to leave this here for others who ran into the same issue and search the issues about it.
At the nightly build in the release tab it also says: "So you can install the nightly version alongside the stable version of our app, if you want to test new features or bug fixes." Maybe this could be clarified if it is a general issue.

**Comment by patzly** [comment]
Thanks for reporting! Yes we mention it in the readme because this should be the purpose of the nightly build, to install it alongside stable. The signatures and package names are different for both versions, so normally it should work with both installed and on my Pixel with Android 14 beta I can confirm that🤔

**Comment by patzly** [comment]
Even updating the stable to 3.3.1 worked for me, so either it has todo with the currently installed version of the nightly (maybe it has to be the same as the update of the stable but that would be weird) or Lineage OS has some changes regarding package installation.

**Comment by vanMacG** [comment]
What also might be the cause: For the stable version, I use the F-Droid builds.
For the nightly I used the one from github.

**Comment by vanMacG** [comment]
> Even updating the stable to 3.3.1 worked for me, so either it has todo with the currently installed version of the nightly (maybe it has to be the same as the update of the stable but that would be weird) or Lineage OS has some changes regarding package installation.

I still have the nightly apk in my download directory. It was Grocy-Android-mlkit-20230619.apk

**Comment by dominiczedler** [comment]
The problem was a change in the content provider authorities... I don't know a solution for this, maybe it is good that this issue exists for people with the same problem, but now with the latest version in all categories, it should not occur again hopefully. Besides it is anyway necessary to uninstall a nightly in case you want to install a newer one, so maybe this is the only solution. Thanks you for reporting, guys.
