### ISSUE TITLE
[3.3.2] missing on F-Droid

### ISSUE THREAD

**Issue by OiledAmoeba** [patzly/grocy-android#780]
Latest available version on F-Droid is 3.3.1

![Screenshot_20230914-144821.png](https://github.com/patzly/grocy-android/assets/14559685/99b5cd6a-9985-412a-9f09-1d6958fd53bb)

**Comment by dominiczedler** [comment]
This will be fixed with a new version.

**Comment by patzly** [comment]
Turns out Google requires me not only to have a valid privacy policy linked in the app which would be fixed with the latest release. Instead a new EU verification for the playment account is required which requires hundrets of proof documents and a national ID which isn't expiring in the next months, so I have to get a new ID before I can make the verification process and again being able to publish updates on Google Play....

**Comment by patzly** [comment]
Update is available on Google Play!
