### ISSUE TITLE
UI enhancement to create Product with openFoodFacs

### ISSUE THREAD

**Issue by stephanfriedrich** [patzly/grocy-android#801]
hello everyone,
first of all, thank you for your user-friendly android app and all the work.

is it possible to make the following ui-enhancement ?

----

## ui-enhancement

as a user, i would like to create a new product and add the product data via "openFoodFacts".
a feedback with the ux element for "start query", "error during query", "unsuccessful query" and "successful query" would be desirable here, so as not to remain uninformed in the event of an error.

thx, have a nice day

**Comment by dominiczedler** [comment]
Hi, this is already implemented and shown if OFF requests are enabled in the app. You just have to scan a product which is not in OFF database (this will be displayed as info text). Other OFF request errors are also displayed on the "choose product" page. I think the problem was in your case that you scanned a barcode of a product which has an empty string as product name (see other issue). Then the field of the product name won't be filled...
