### ISSUE TITLE
extend product-meta-data with openFoodFacts data

### ISSUE THREAD

**Issue by stephanfriedrich** [patzly/grocy-android#804]
hi, thanks again for your great work on this application.

as a user, i would like to be able to edit an existing product and select and enter the metadata such as category, image, packaging from openFoodFacts.

**Comment by dominiczedler** [comment]
Thanks, also tracked on #538. Please don't open a new issue for every little bit of information. All 5 issues you have created were related to each other so this could easily have been a single issue.

Editing a product with OFF is slightly more work or needs implementation ideas because one product can have many barcodes. And this would need a selection which barcode you want to choose for information. Maybe in the future there is a way for that, but this is unlikely.
