### ISSUE TITLE
Newest release 3.4.2 not available for download

### ISSUE THREAD

**Issue by alkuzman** [patzly/grocy-android#813]
Not available both on PlayStore and on FDroid  I didn't find any info that it was not released, so maybe you are not aware. Sorry if it was intentional

**Comment by patzly** [comment]
Thanks, F-Droid can take some weeks until their servers are building, we have no control over that. Google Play requires a new release because the update was taken down as my homepage was not accessable for some days including the required privacy policy for Grocy, I will make a release in the next days.
