### ISSUE TITLE
change default currency

### ISSUE THREAD

**Issue by eskoONE** [patzly/grocy-android#836]
It seems like the currency used in the android app is the app. I haven't set up my own server yet, so this might be related to that, but it seems like the currency used is bound to the language used. I noticed this, when changing the language from English to German. An option to pick the preferred currency would be a nice to have feature. 

Thanks.

**Comment by dominiczedler** [comment]
That's intended. Why do you report an issue, if you didn't try the behavior with your server first? The demo server changes when you switch the language because the demo data should also be in the right language. An thus the currency displayed changes for this specific language (USD for EN, EUR for DE and so on).

**Comment by patzly** [comment]
No it should not be app-related, what you may have seen is the language-specific demo server. When you have selected the demo server instead of your own server, the language-matching demo server url is automatically selected which has the country-specific currency set. With your own server you have to set the currency in the config file in your server installation.

**Comment by eskoONE** [comment]
> Why do you report an issue, if you didn't try the behavior with your server first? 

Because I used the test server for the purpose of testing the capabilities of the app. It's the first thing that I noticed and a quick search here and Google didn't show any results.

Also, the feedback button in the app leads me here, so I assumed that's the preferred way of feedback. Sorry for the inconvenience. 

> The demo server changes when you switch the language because the demo data should also be in the right language. An thus the currency displayed changes for this specific language (USD for EN, EUR for DE and so on).

This as an answer would have been sufficient. Thanks for your time and effort. 

> With your own server you have to set the currency in the config file in your server installation.

That's the answer I was looking for. Thanks a lot.

**Comment by patzly** [comment]
@eskoONE It's fine to ask that! :)
