### ISSUE TITLE
Add support for server 4.2.0

### ISSUE THREAD

**Issue by ulu** [patzly/grocy-android#855]
After updating the server from 4.1.0 to 4.2 I'll get some warnings regarding incompatibilities of grocy-android.

Would it be possible to make grocy-android compatible again?

**Comment by Gerben321** [comment]
As far as I can see it is compatible, I haven't found anything strange. So removing the warning would be great for sure.

**Comment by patzly** [comment]
Here is an answer to that, with the update that we both have a full-time job now: https://github.com/patzly/grocy-android/issues/558#issuecomment-1165495014

We notice ourself when a new Grocy version is released but an update simply needs time, so no extra issue required. Otherwise all incompatibility issues are very welcome.
