### ISSUE TITLE
Support nested storage locations

### ISSUE THREAD

**Issue by Saturo78** [patzly/grocy-android#861]
My storage locations are organised as follows:

Küche\Vorratsschrank\Ebene 1

Unfortunately, the consumption storage location only works if it matches completely.
I would like to have that consuption location set to Küche\Vorratsschrank 
also finds stock entries in 
Küche\Vorratschrank\Ebene...

**Comment by patzly** [comment]
This isn't supported by the web interface I think because there is just a simple dropdown. The API needs exactly one `location_id` parameter and this would require too much logic which should be done by the server. I think the only solution is to select the exact name or to simplify the location scheme.
