### ISSUE TITLE
Consider KMP

### ISSUE THREAD

**Issue by Nailik** [patzly/grocy-android#891]
Hi,

did you ever consider converting it to a KMP (Kotlin Multiplatform) to bring it to iOS?

I know there would be loads to do like

1. Java to Kotlin
2. XML to Compose
3. Extracting all Android specific code and implementing iOS equavialents

So as a small first step, what do you think about switching to Kotlin?
- In my opinion it's a far superior language

**Comment by patzly** [comment]
Hi, sadly there are a tons of reasons that speak agains that:

- When I created the whole app together with my twin brother we didn't know much about efficient programming, so
- The whole code is a mess and would require a huge reunderstanding of every aspect to respect common patterns
- My brother switched to Apple devices a while ago so I'm the sole maintainer now
- I don't have much time beside my studies and work and my private life
- I would like to spend my remaining free time on my other apps which aren't as huge and messy and hard to maintain as Grocy Android like Tack and Stiefo where I can focus on design and new features
- It would require an entire rewrite which means again hundrets hours of work, but the project already escalated in it's first steps regarding it's size and the limited benefit because it's such a niche project and already required too much time to create and it isn't nearly finished at all

I hope you now understand why that's not an option for me, despite that I really like Kotlin and Compose, too.

**Comment by Nailik** [comment]
I understand - actually i was baffled to see everything is Kotlin and XML because the ui looks pretty much like Material3 and i wasn't expecting that at all.
Keep up the great work!

**Comment by patzly** [comment]
There is the great MDC Android library project which is in Java and only for Views/XML, and that's always the most up-to-date version of Material Design, so I'm kinda glad I still use views because Compose still hasn't every component available and Views are a bit more customizable and easier to animate :)
