### ISSUE TITLE
Modern&fast GUI

### ISSUE THREAD

**Issue by disgran** [patzly/grocy-android#896]
It would be nice if it had a graphical interface like the ones in restaurant POS terminals, so it could be placed in the kitchen for better food management. This way it is a bit rustic. Please consider putting in a more up-to-date GUI. Thanks for your contribution.

**Comment by patzly** [comment]
Sure you mean this app? Because Grocy Android follows the most modern design system I would say, Google's Material Design 3. If you think that's not up-to-date and unintuitive then I unfortunally can't do anything. Most people like my apps especially because of their modern and clean design for smartphones. That also means that it's not intended that the design is the same as a restaurant terminal, that would most people consider as ugly regarding design I think.

**Comment by disgran** [comment]
Sorry, it was just an opinion, I didn't mean to upset you.
